# Jekyll configuration

name: Dekuan
description: '
<div style="text-align:center;">
  <img src="/images/photo.jpg" alt="My Photo" style="width:150px; margin-bottom:15px;">
  <br>
  <span style="font-size:18px; font-weight:bold;">Dekuan Dong</span>
</div>'
title: "Dekuan Dong"
email: "dkdong21@m.fudan.edu.cn"


# url is currently only used only for the RSS feed in feed.xml
url: "https://dongdekuan.github.io"

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""

# These can be '' to hide the Github or Gitlab nav buttons
github: 'scotte/jekyll-clean'
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

# Configuration settings cannot be changed for GitHub Pages sites
lsi: false
safe: true
source: 'https://github.com/dongdekuan/ddk.github.io'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rough

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
